### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by TylerAdamMartinez** [Dagar-Rehan/Hatchling-Web-Frontend#15]
Success Criteria:  
* The user click cancel when prompted by the download button   
   => no file was downloaded
* The user enters an empty string or all whitespace   
   => no file was downloaded
* The user enters a name without the proper extension  
   => file downloaded with the extension added to the end of the filename
* The user enters a name with the proper extension     
   => file downloaded

**Comment by Dagar-Rehan** [comment]
#19
